name: SoulBossSystem
author: Elia, D1p4k, Zopnote
main: de.elia.PluginMain
softdepend:
  - WorldGuard
  - SoulLibrary
version: 1.0.0.pre.1
api-version: 1.19
description: This plugin was written for SoulSMP. I put a lot of effort into it and I hope you really like it.
             I know this plugin changes the entire server, but sometimes a change is important. This plugin 
             ensures that you can earn your own bossfight. But since I still need a lot of ideas, feel free 
             to write an idea with the command /mobidea an idea.
permissions:
  soulboss.give:
    description: If the player has this permission, he can execute the bossgive command.
  soulboss.plugin:
    description: With this permission, players can query all important information from this plugin.
  soulboss.fight:
    description: With this permission, players can spawn the boss.
  soulboss.world:
    description: With this permission you can teleport in the bossfight world.
commands:
  bosshelp:
    description: Here every player can get all the information from the recipes, commands and the bosses.
  mobidea:
    description: The player can submit ideas for improvements or extensions of this plugin.
  bossgive:
    description: Gives the player the items he selects.
  bossfight:
    description: Players can use it to start the bossfight (or use the spawn egg method).
  soulboss:
    description: Players can use it to read information about the plugin.
  tpworld:
    description: Teleport the player in a other world.
  trustplayer:
    description: Trusted a player for a bossfight!
