package de.elia.api.enums;

public enum VoiceType {
  ALLAY_DE_FIRST_TALK,
  ALLAY_DE_PROMPT_GO,
  ALLAY_DE_SHOW_VILLAGE,
  ALLAY_DE_SHOW_NPCS,
  ALLAY_DE_PROMPT_KILL_PIG,
  ALLAY_DE_EXPLAIN_MONEY,
  ALLAY_DE_CONGRATION_SWORD,

  ALLAY_DE_STORY_BEGINN,
  ALLAY_DE_STORY_LINE_ONE,
  ALLAY_DE_STORY_LINE_TWO,
  ALLAY_DE_STORY_LINE_THREE,
  ALLAY_DE_STORY_LINE_FOUR,
  ALLAY_DE_STORY_LINE_FIVE,
  ALLAY_DE_STORY_LINE_SIX,
  ALLAY_DE_STORY_LINE_SEVEN,

  ALLAY_DE_STORY_SOUL_CRAFTET_COMPLETE
}
